//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net.Appclusive.Public {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Net.Appclusive.Public.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must either specify AbsoluteExpiration or RelativeExpiration..
        /// </summary>
        internal static string ApprovalBase_ValidateInstance__InvalidCombinationAbsoluteExpirationRelativeExpiration {
            get {
                return ResourceManager.GetString("ApprovalBase_ValidateInstance__InvalidCombinationAbsoluteExpirationRelativeExpira" +
                        "tion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must either specify RoleId or UserId..
        /// </summary>
        internal static string ApprovalBase_ValidateInstance__InvalidCombinationRoleIdUserId {
            get {
                return ResourceManager.GetString("ApprovalBase_ValidateInstance__InvalidCombinationRoleIdUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Attribute &apos;{1}&apos; from behaviourDefinition &apos;{2}&apos; has not been implemented or can be derived..
        /// </summary>
        internal static string ModelValidator__Missing_Attribute {
            get {
                return ResourceManager.GetString("ModelValidator__Missing_Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State &apos;Decommissioned&apos; is not defined as a destination in any state transition..
        /// </summary>
        internal static string StateMachine_TryValidate__Decommissioned {
            get {
                return ResourceManager.GetString("StateMachine_TryValidate__Decommissioned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be at exactly one state transition with state &apos;Decommissioned&apos; as source and &apos;Finalise&apos; as action and &apos;FinalState&apos; as destination defined..
        /// </summary>
        internal static string StateMachine_TryValidate__Decommissioned_Finalise_FinalState {
            get {
                return ResourceManager.GetString("StateMachine_TryValidate__Decommissioned_Finalise_FinalState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate state transition &apos;{0}-{1}:{2}&apos; defined..
        /// </summary>
        internal static string StateMachine_TryValidate__Duplicate_State_Action {
            get {
                return ResourceManager.GetString("StateMachine_TryValidate__Duplicate_State_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be exactly one state transition with state &apos;ErrorState&apos; as source and &apos;Remedy&apos; as action defined..
        /// </summary>
        internal static string StateMachine_TryValidate__ErrorState_Remedy {
            get {
                return ResourceManager.GetString("StateMachine_TryValidate__ErrorState_Remedy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be exactly one state transition with &apos;Finalise&apos; as action defined..
        /// </summary>
        internal static string StateMachine_TryValidate__Finalise {
            get {
                return ResourceManager.GetString("StateMachine_TryValidate__Finalise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be exactly one state transition with state &apos;FinalState&apos; as destination defined..
        /// </summary>
        internal static string StateMachine_TryValidate__FinalState {
            get {
                return ResourceManager.GetString("StateMachine_TryValidate__FinalState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be exactly one state transition with state &apos;FinalState&apos; as destination and &apos;Finalise&apos; as action defined..
        /// </summary>
        internal static string StateMachine_TryValidate__FinalState_Finalise {
            get {
                return ResourceManager.GetString("StateMachine_TryValidate__FinalState_Finalise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State &apos;FinalState&apos; cannot be the source of a state transition..
        /// </summary>
        internal static string StateMachine_TryValidate__FinalState_Source {
            get {
                return ResourceManager.GetString("StateMachine_TryValidate__FinalState_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be exactly one state transition with &apos;Initialise&apos; as action defined..
        /// </summary>
        internal static string StateMachine_TryValidate__InitialState {
            get {
                return ResourceManager.GetString("StateMachine_TryValidate__InitialState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status &apos;InitialState&apos; cannot be the destination of a state transition..
        /// </summary>
        internal static string StateMachine_TryValidate__InitialState_Destination {
            get {
                return ResourceManager.GetString("StateMachine_TryValidate__InitialState_Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be exactly one state transition with state &apos;InitialState&apos; as source and &apos;Initialise&apos; as action defined..
        /// </summary>
        internal static string StateMachine_TryValidate__InitialState_Initialise {
            get {
                return ResourceManager.GetString("StateMachine_TryValidate__InitialState_Initialise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be at least one state transition with state &apos;InitialState&apos; as source defined..
        /// </summary>
        internal static string StateMachine_TryValidate__InitialState_Source {
            get {
                return ResourceManager.GetString("StateMachine_TryValidate__InitialState_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action &apos;Remedy&apos; is not defined as an action in any state transition..
        /// </summary>
        internal static string StateMachine_TryValidate__Remedy {
            get {
                return ResourceManager.GetString("StateMachine_TryValidate__Remedy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving StateMachine for type &apos;{0}&apos; via instance type &apos;{1}&apos; ....
        /// </summary>
        internal static string StateMachineBuilder_StateMachineBuilder__RetrievingStateMachine1 {
            get {
                return ResourceManager.GetString("StateMachineBuilder_StateMachineBuilder__RetrievingStateMachine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieved StateMachine for type &apos;{0}&apos; via instance type &apos;{1}&apos;. States: {2}. Actions:{3}..
        /// </summary>
        internal static string StateMachineBuilder_StateMachineBuilder__RetrievingStateMachine2 {
            get {
                return ResourceManager.GetString("StateMachineBuilder_StateMachineBuilder__RetrievingStateMachine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StateMachine for Model &apos;{0}&apos; is invalid. Implementation of derived Model &apos;{1}&apos; is missing action &apos;{2}&apos;..
        /// </summary>
        internal static string StateMachineValidator_TryValidate__DerivedModelMissingAction {
            get {
                return ResourceManager.GetString("StateMachineValidator_TryValidate__DerivedModelMissingAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StateMachine for Model &apos;{0}&apos; is invalid. Implementation of derived Model &apos;{1}&apos; is missing state &apos;{2}&apos;..
        /// </summary>
        internal static string StateMachineValidator_TryValidate__DerivedModelMissingState {
            get {
                return ResourceManager.GetString("StateMachineValidator_TryValidate__DerivedModelMissingState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StateMachine for Model &apos;{0}&apos; is invalid. Implementation of inherited Behaviour &apos;{1}&apos; is missing action &apos;{2}&apos;..
        /// </summary>
        internal static string StateMachineValidator_TryValidate__InheritedBehaviourMissingAction {
            get {
                return ResourceManager.GetString("StateMachineValidator_TryValidate__InheritedBehaviourMissingAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StateMachine for Model &apos;{0}&apos; is invalid. Implementation of inherited Behaviour &apos;{1}&apos; is missing state &apos;{2}&apos;..
        /// </summary>
        internal static string StateMachineValidator_TryValidate__InheritedBehaviourMissingState {
            get {
                return ResourceManager.GetString("StateMachineValidator_TryValidate__InheritedBehaviourMissingState", resourceCulture);
            }
        }
    }
}
